[package]
name = "smt-nocturne-prolog-kb-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
argh = "0.1.13"
oxigraph = { version = "*", default-features = false }
oxrdfio = "0.1.7"
